# Generated by Django 5.2.4 on 2025-08-08 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='crated_at',
            new_name='created_at',
        ),
    ]
